### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Got 12 and 11 in dimension 2 (The offending index is 1)

### ISSUE THREAD

**Issue by gayathri81** [obss/sahi#300]
Hello, 
Thanks for sharing your work. I tried running standard inference using yolov5s6 model, but getting this weird error of tensors size match.
When I tried using yolov5 directly, there is no issue, but getting results through perform inference of Yolov5DetectionModel is causing size issue.
**Code:**

        import cv2
        import torch
        import sahi
        from sahi.model import Yolov5DetectionModel
        from sahi.predict import get_prediction
        from sahi.utils.cv import read_image

        yolov5_model_path = 'models/yolov5s6.pt'

        #Instantiate a detection model by defining model weight path and other parameters:
        detection_model = Yolov5DetectionModel(
              model_path=yolov5_model_path,
              confidence_threshold=0.3,
              device="cpu", # or 'cuda:0'
              #device='cuda:0'
         )
         img = cv2.imread("demo_data/small-vehicles1.jpeg")
         print("img size: ", img.shape)

         result = get_prediction("demo_data/small-vehicles1.jpeg", detection_model)
**Error:**
         Traceback (most recent call last):
         File "inference/standard_inference.py", line 26, in <module>
            result = get_prediction("demo_data/small-vehicles1.jpeg", detection_model)
         File "ws_36/lib/python3.6/site-packages/sahi/predict.py", line 63, in get_prediction
            detection_model.perform_inference(np.ascontiguousarray(image_as_pil), image_size=image_size)
         File "ws_36/lib/python3.6/site-packages/sahi/model.py", line 433, in perform_inference
            prediction_result = self.model(image)
         File "ws_36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
            result = self.forward(*input, **kwargs)
         File "ws_36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
            return func(*args, **kwargs)
         File "ws_36/lib/python3.6/site-packages/yolov5/models/common.py", line 347, in forward
            y = self.model(x, augment, profile)[0]  # forward
         File "ws_36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
            result = self.forward(*input, **kwargs)
         File "ws_36/lib/python3.6/site-packages/yolov5/models/yolo.py", line 123, in forward
            return self._forward_once(x, profile, visualize)  # single-scale inference, train
         File "ws_36/lib/python3.6/site-packages/yolov5/models/yolo.py", line 146, in _forward_once
            x = m(x)  # run
         File "ws_36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
            result = self.forward(*input, **kwargs)
         File "ws_36/lib/python3.6/site-packages/yolov5/models/common.py", line 273, in forward
            return torch.cat(x, self.d)
        RuntimeError: Sizes of tensors must match except in dimension 1. Got 12 and 11 in dimension 2 (The offending index is 1)

Image is a 3 channelled image, shape:  (580, 1068, 3).

**But when tried yolov5 model directly from torch it ran without any error**.

        import cv2
        import torch
        import sahi
        from sahi.model import Yolov5DetectionModel
        from sahi.predict import get_prediction
        from sahi.utils.cv import read_image

        model = torch.hub.load('ultralytics/yolov5', 'yolov5s6')
        result = model(mat)

It will be really great if you can help me solve this issue.

**Comment by fcakyon** [comment]
Hello @gayathri81 thanks a lot for your interest in `SAHI`!

Unfortunately I cannot recreate the issue in the yolov5+sahi colab notebook: https://colab.research.google.com/github/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb

Can you update your yolov5 and sahi versions to the latest and try again? `pip install -U yolov5 sahi`
