### ISSUE TITLE
Mmdet: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kadirnar** [obss/sahi#382]
Installation:
```
pip install sahi
pip install mmcv-full==1.4.4 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
pip install mmdet==2.21.0
```
Code: 
```
from sahi.utils.mmdet import (
    download_mmdet_cascade_mask_rcnn_model,
    download_mmdet_config,
)

# import required functions, classes
from sahi.model import MmdetDetectionModel
from sahi.utils.cv import read_image
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict
from IPython.display import Image

model_path = 'models/cascade_mask_rcnn.pth'
download_mmdet_cascade_mask_rcnn_model(model_path)
config_path = download_mmdet_config(model_name="cascade_rcnn", config_file_name="cascade_mask_rcnn_r50_fpn_1x_coco.py",)

# download test images into demo_data folder
download_from_url('https://raw.githubusercontent.com/obss/sahi/main/demo/demo_data/small-vehicles1.jpeg', 'demo_data/small-vehicles1.jpeg')
download_from_url('https://raw.githubusercontent.com/obss/sahi/main/demo/demo_data/terrain2.png', 'demo_data/terrain2.png')

detection_model = MmdetDetectionModel(
    model_path=model_path,
    config_path=config_path,
    confidence_threshold=0.4,
    device="cpu", # or 'cuda:0'
)
result = get_prediction("demo_data/small-vehicles1.jpeg", detection_model)
result = get_prediction(read_image("demo_data/small-vehicles1.jpeg"), detection_model)

result.export_visuals(export_dir="demo_data/")

Image("demo_data/prediction_visual.png")
```

Error Message:

```
02/12/2022 20:48:03 - INFO - root -   Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
02/12/2022 20:48:03 - INFO - root -   Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
Traceback (most recent call last):
  File "/home/kadir/Desktop/kadirnar/github/sahi/yolox_fix.py", line 21, in <module>
    detection_model = MmdetDetectionModel(
  File "/home/kadir/Desktop/kadirnar/github/sahi/sahi/model.py", line 71, in __init__
    self.load_model()
  File "/home/kadir/Desktop/kadirnar/github/sahi/sahi/model.py", line 176, in load_model
    from mmdet.apis import init_detector
  File "/home/kadir/virtualenvironment/sahi/lib/python3.8/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/kadir/virtualenvironment/sahi/lib/python3.8/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/home/kadir/virtualenvironment/sahi/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/kadir/virtualenvironment/sahi/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/kadir/virtualenvironment/sahi/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```

**Comment by fcakyon** [comment]
@kadirnar what is your cuda, pytorch and torchvision version? How did you install cuda and pytorch? What is your GPU model?

What is the output of this code snippet:

```python
import torch
print(torch.cuda.is_available())
```

**Comment by kadirnar** [comment]
Output: ```True```

I am running it with cpu while predicting.
Torch Version: 1.10.2
Cuda Version: 11.3
TorchVison Version: 0.11.3

I ran this code for torch setup:
pip install mmcv-full==1.4.4 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html

When I install Torch from the pytorch site, there is no error. Most likely, the installation commands in the readme section are incorrect.

**Comment by fcakyon** [comment]
> I am running it with cpu while predicting.

Its still important to know which GPU do you have.

> I ran this code for torch setup:
> pip install mmcv-full==1.4.4 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html

This command does not install torch, it installs `mmcv-full`. Have you installed the `torch` and `cuda` via `conda`?
