### ISSUE TITLE
Unexpected behavior with zero width or zero height bool mask

### ISSUE THREAD

**Issue by vincent-vdb** [obss/sahi#389]
Hi and thanks a lot for your work!

When running the library, we encountered an issue in `annotation.py`, when the output bool mask of `get_bbox_from_bool_mask()` is `None`. It happened for example because of having a zero width or zero height mask, thus raising a `ValueError`.

**Comment by fcakyon** [comment]
Thanks a lot for reporting your issue @vincent-vdb!

Which model are you using? MMDetection/YOLOv5/Detectron2?

**Comment by vincent-vdb** [comment]
Thanks for your quick answer. We are using MMDet, we actually have a simple fix proposal, but it seems I can't push a new branch to propose it.

Basically, in `annotation.py`, line 539, switching the `raise ValueError` to `self.mask = None` fixes the issue on our side.

**Comment by fcakyon** [comment]
@vincent-vdb you can fork this repo, push your update to a branch in your fork, then open a PR to this repo :rocket:. We are open to PRs :+1: 

I have [opened a PR to fix this](https://github.com/obss/sahi/pull/390) can you test it by installing the sahi from branch `handle-invalid-mask`?

You have to first uninstall your current `sahi` installation by:
```bash
pip uninstall sahi -y
```

Then install `sahi` from branch:
```bash
pip install git+https://github.com/obss/sahi.git@handle-invalid-mask
```

**Comment by vincent-vdb** [comment]
This PR does not fix the issue on my side :/

Here is the traceback if it can be of any help:
```
Traceback (most recent call last):
  File "/opt/conda/bin/sahi", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.8/site-packages/sahi/cli.py", line 24, in app
    fire.Fire(sahi_app)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/sahi/predict.py", line 477, in predict
    prediction_result = get_sliced_prediction(
  File "/opt/conda/lib/python3.8/site-packages/sahi/predict.py", line 247, in get_sliced_prediction
    prediction_result = get_prediction(
  File "/opt/conda/lib/python3.8/site-packages/sahi/predict.py", line 88, in get_prediction
    detection_model.convert_original_predictions(
  File "/opt/conda/lib/python3.8/site-packages/sahi/model.py", line 144, in convert_original_predictions
    self._create_object_prediction_list_from_original_predictions(
  File "/opt/conda/lib/python3.8/site-packages/sahi/model.py", line 344, in _create_object_prediction_list_from_original_predictions
    object_prediction = ObjectPrediction(
  File "/opt/conda/lib/python3.8/site-packages/sahi/prediction.py", line 75, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.8/site-packages/sahi/annotation.py", line 539, in __init__
    raise ValueError("Invalid boolean mask.")
ValueError: Invalid boolean mask.
```

**Comment by fcakyon** [comment]
@vincent-vdb with this update, it should skip the predictions with invalid masks: https://github.com/obss/sahi/blob/3c5649847982b204e29e8aa853796cc8e201c6c2/sahi/model.py#L321

I dont understand how can it reach `File "/opt/conda/lib/python3.8/site-packages/sahi/model.py", line 344, in _create_object_prediction_list_from_original_predictions` when there is an invalid mask.

**Comment by fcakyon** [comment]
@vincent-vdb found the issue and updated. Can you please remove sahi and install again from branch and check if its fixed?

**Comment by vincent-vdb** [comment]
It seems to be working now, thanks. At least I did not encounter the issue for the moment on the same data. Hope you can merge this PR soon!

**Comment by fcakyon** [comment]
@vincent-vdb it is merged, you can install from master till next release!

Thanks for your feedback 🚀
