### ISSUE TITLE
mmDetection issue

### ISSUE THREAD

**Issue by zhuofalin** [obss/sahi#396]
I run this demo from **https://colab.research.google.com/github/obss/sahi/blob/main/demo/inference_for_mmdetection.ipynb** and find error 

> psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=5432)

> psutil package

-> this error was shown in result.to_fiftyone_detections()[0] [inference_for_mmdetection.py (line 117) ] in this project
by the way, i work in win10 system,maybe it is reason~~~

**Comment by zhuofalin** [comment]
wanted to help~~

**Comment by fcakyon** [comment]
Hello @zhuofalin, so you have run the demo notebook in your local windows 10 machine, and not in colab right? Cause fiftyone may cause some issues on Google Colab.

If you could paste the full error log I can help you fix your issue 👍

**Comment by zhuofalin** [comment]
**Thank you for your reply and help, the following is the error message when the program is running.**
Uncaught exception
Traceback (most recent call last):
  File "H:/testProgect/inference_for_mmdetection.py", line 117, in <module>
    result.to_fiftyone_detections()[0]
  File "D:\anaconda\lib\site-packages\sahi\prediction.py", line 201, in to_fiftyone_detections
    import fiftyone as fo
  File "D:\anaconda\lib\site-packages\fiftyone\__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "D:\anaconda\lib\site-packages\fiftyone\__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "D:\anaconda\lib\site-packages\fiftyone\core\odm\database.py", line 80, in establish_db_conn
    port = _db_service.port
  File "D:\anaconda\lib\site-packages\fiftyone\core\service.py", line 295, in port
    return self._wait_for_child_port()
  File "D:\anaconda\lib\site-packages\fiftyone\core\service.py", line 179, in _wait_for_child_port
    return find_port()
  File "D:\anaconda\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "D:\anaconda\lib\site-packages\retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "D:\anaconda\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "D:\anaconda\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "D:\anaconda\lib\site-packages\fiftyone\core\service.py", line 166, in find_port
    for child in fosu.normalize_wrapper_process(self.child).children(
  File "D:\anaconda\lib\site-packages\psutil\__init__.py", line 271, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=5432)
![2022-02-17 164656](https://user-images.githubusercontent.com/29940053/154438900-a62fd09c-0d90-4ba2-8d7f-c535df613895.png)
👍  thank you ~~

**Comment by zhuofalin** [comment]
(*^_^*) 
The version of **sahi** is 0.9.0 and the version of **fiftyone** is 0.14.4 
😀

**Comment by fcakyon** [comment]
@zhuofalin I have tried running demo notebooks on Windows 10 with `sahi==0.9.0` and `fiftyone==0.14.4` and there is no error/issue when calling `to_fiftyone_detections()` method. You can try a fresh install on a new conda environment or open an issue on [fiftyone repo](https://github.com/voxel51/fiftyone).

**Comment by zhuofalin** [comment]
Done!!  😀
Thank you for your help~ 谢谢👏
👍
