### ISSUE TITLE
sahi coco yolov5 , list index out of range

### ISSUE THREAD

**Issue by monkeycc** [obss/sahi#525]
`https://github.com/obss/sahi/issues/524`
Because there is a problem
I don't know how to solve it
So only data sets can be excluded
Is there a problem
As expected, abnormal conditions were found

`sahi coco yolov5 --image_dir D:\sahi\demo\demo_data\runs\slice_coco\PCB_COCO_images_640_02 --dataset_json_path D:\sahi\demo\demo_data\runs\slice_coco\PCB_COCO_640_02.json  --train_split 0.9`

labelImg
exp/train/XXX.txt
```
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\labelImg\labelImg.py", line 738, in file_item_double_clicked
    self.load_file(filename)
  File "D:\anaconda3\lib\site-packages\labelImg\labelImg.py", line 1111, in load_file
    self.show_bounding_box_from_annotation_file(file_path)
  File "D:\anaconda3\lib\site-packages\labelImg\labelImg.py", line 1144, in show_bounding_box_from_annotation_file
    self.load_yolo_txt_by_filename(txt_path)
  File "D:\anaconda3\lib\site-packages\labelImg\labelImg.py", line 1557, in load_yolo_txt_by_filename
    t_yolo_parse_reader = YoloReader(txt_path, self.image)
  File "D:\anaconda3\lib\site-packages\libs\yolo_io.py", line 112, in __init__
    self.parse_yolo_format()
  File "D:\anaconda3\lib\site-packages\libs\yolo_io.py", line 143, in parse_yolo_format
    label, x_min, y_min, x_max, y_max = self.yolo_line_to_shape(class_index, x_center, y_center, w, h)
  File "D:\anaconda3\lib\site-packages\libs\yolo_io.py", line 125, in yolo_line_to_shape
    label = self.classes[int(class_index)]
IndexError: list index out of range
```

exp/train/XXX1.txt
exp/train/XXX2.txt
```

6 0.36640625000000004 0.946875 0.0546875 0.037500000000000006
4 0.3953125 0.91796875 0.021875000000000002 0.0203125

6 0.36640625000000004 0.146875 0.0546875 0.037500000000000006
4 0.3953125 0.11796875000000001 0.021875000000000002 0.0203125


```

**Comment by fcakyon** [comment]
@monkeycc you have to update your annotations so that minimum category id is 0.
