### ISSUE TITLE
slice imge has error, "Too many open files"

### ISSUE THREAD

**Issue by jiangwenj02** [obss/sahi#565]
**Traceback**

```python
Traceback (most recent call last):
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/sahi/utils/cv.py", line 156, in read_image_as_pil
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/PIL/Image.py", line 3092, in open
OSError: [Errno 24] Too many open files: 'mmdetection/data/tianyan/images/train/DJI_0591MP416.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/bin/sahi", line 8, in <module>
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/sahi/cli.py", line 31, in app
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/sahi/scripts/slice_coco.py", line 59, in slice
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/sahi/slicing.py", line 468, in slice_coco
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/sahi/slicing.py", line 311, in slice_image
  File "/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/sahi/utils/cv.py", line 162, in read_image_as_pil
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
OSError: [Errno 24] Too many open files: '/home1/users/jiangwenj02/anaconda3/envs/mmtrack/lib/python3.7/site-packages/skimage/__init__.py'
```

**Comment by fcakyon** [comment]
@jiangwenj02 sorry for the late reply.

Can you give detail on which functions or cli command you have used to get this error?
