### ISSUE TITLE
 RuntimeError:  undefined value has_torch_function_variadic:

### ISSUE THREAD

**Issue by MLDovakin** [obss/sahi#607]
my libs :
sahi==0.10.7
torchvision==0.13.1
torch==1.6.0+cu101
detectron2==0.6

But when I try to run AutoDetectionModel.from_pretrained with detectron2 it throws an error

````
model_path = Detectron2TestConstants.FASTERCNN_MODEL_ZOO_NAME

download_from_url('https://raw.githubusercontent.com/obss/sahi/main/demo/demo_data/small-vehicles1.jpeg', 'demo_data/small- 
vehicles1.jpeg')
download_from_url('https://raw.githubusercontent.com/obss/sahi/main/demo/demo_data/terrain2.png', 'demo_data/terrain2.png')
detection_model = AutoDetectionModel.from_pretrained(model_type='detectron2',
                                                     model_path=model_path,
                                                     config_path=model_path,
                                                     confidence_threshold=0.5,
                                                     image_size=640,
                                                     device="cpu", # or 'cuda:0')
````
Logs

````
RuntimeError                              Traceback (most recent call last)
[<ipython-input-5-6c3be4aaa524>](https://localhost:8080/#) in <module>
      5     confidence_threshold=0.5,
      6     image_size=640,
----> 7     device="cpu", # or 'cuda:0'
      8 )

13 frames
[/usr/local/lib/python3.7/dist-packages/sahi/auto_model.py](https://localhost:8080/#) in from_pretrained(model_type, model_path, model, config_path, device, mask_threshold, confidence_threshold, category_mapping, category_remapping, load_at_init, image_size, **kwargs)
     73             load_at_init=load_at_init,
     74             image_size=image_size,
---> 75             **kwargs,
     76         )
     77 

[/usr/local/lib/python3.7/dist-packages/sahi/model.py](https://localhost:8080/#) in __init__(self, model_path, model, config_path, device, mask_threshold, confidence_threshold, category_mapping, category_remapping, load_at_init, image_size)
     75                 self.set_model(model)
     76             else:
---> 77                 self.load_model()
     78 
     79     def load_model(self):

[/usr/local/lib/python3.7/dist-packages/sahi/model.py](https://localhost:8080/#) in load_model(self)
    527         check_requirements(["torch", "detectron2"])
    528 
--> 529         from detectron2.config import get_cfg
    530         from detectron2.data import MetadataCatalog
    531         from detectron2.engine import DefaultPredictor

[/usr/local/lib/python3.7/dist-packages/detectron2/data/__init__.py](https://localhost:8080/#) in <module>
      2 from . import transforms  # isort:skip
      3 
----> 4 from .build import (
      5     build_batch_data_loader,
      6     build_detection_test_loader,

[/usr/local/lib/python3.7/dist-packages/detectron2/data/build.py](https://localhost:8080/#) in <module>
     11 
     12 from detectron2.config import configurable
---> 13 from detectron2.structures import BoxMode
     14 from detectron2.utils.comm import get_world_size
     15 from detectron2.utils.env import seed_all_rng

[/usr/local/lib/python3.7/dist-packages/detectron2/structures/__init__.py](https://localhost:8080/#) in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 from .boxes import Boxes, BoxMode, pairwise_iou, pairwise_ioa, pairwise_point_box_distance
----> 3 from .image_list import ImageList
      4 
      5 from .instances import Instances

[/usr/local/lib/python3.7/dist-packages/detectron2/structures/image_list.py](https://localhost:8080/#) in <module>
      6 from torch.nn import functional as F
      7 
----> 8 from detectron2.layers.wrappers import shapes_to_tensor
      9 
     10 

[/usr/local/lib/python3.7/dist-packages/detectron2/layers/__init__.py](https://localhost:8080/#) in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates.
----> 2 from .batch_norm import FrozenBatchNorm2d, get_norm, NaiveSyncBatchNorm, CycleBatchNormList
      3 from .deform_conv import DeformConv, ModulatedDeformConv
      4 from .mask_ops import paste_masks_in_image
      5 from .nms import batched_nms, batched_nms_rotated, nms, nms_rotated

[/usr/local/lib/python3.7/dist-packages/detectron2/layers/batch_norm.py](https://localhost:8080/#) in <module>
      2 import torch
      3 import torch.distributed as dist
----> 4 from fvcore.nn.distributed import differentiable_all_reduce
      5 from torch import nn
      6 from torch.nn import functional as F

[/usr/local/lib/python3.7/dist-packages/fvcore/nn/__init__.py](https://localhost:8080/#) in <module>
      2 from .activation_count import activation_count, ActivationCountAnalysis
      3 from .flop_count import flop_count, FlopCountAnalysis
----> 4 from .focal_loss import (
      5     sigmoid_focal_loss,
      6     sigmoid_focal_loss_jit,

[/usr/local/lib/python3.7/dist-packages/fvcore/nn/focal_loss.py](https://localhost:8080/#) in <module>
     50 
     51 
---> 52 sigmoid_focal_loss_jit: "torch.jit.ScriptModule" = torch.jit.script(sigmoid_focal_loss)
     53 
     54 

/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)

[/usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py](https://localhost:8080/#) in try_compile_fn(fn, loc)
    581         # Setter is optional, so it may not exist.
    582         setter_name = property_stub.def_.setter_name()
--> 583         fset = cpp_module._get_method(setter_name.name) if setter_name else None
    584         script_module.__dict__[property_name] = property(property_name, fget, fset)  # type: ignore[arg-type]
    585 

/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)

RuntimeError: 
undefined value has_torch_function_variadic:
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2468
    :class:`~torch.nn.InstanceNorm3d` for details.
    """
    if has_torch_function_variadic(input, running_mean, running_var, weight, bias):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return handle_torch_function(
            instance_norm,
'binary_cross_entropy_with_logits' is being compiled since it was called from 'sigmoid_focal_loss'
  File "/usr/local/lib/python3.7/dist-packages/fvcore/nn/focal_loss.py", line 36
    targets = targets.float()
    p = torch.sigmoid(inputs)
    ce_loss = F.binary_cross_entropy_with_logits(inputs, targets, reduction="none")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    p_t = p * targets + (1 - p) * (1 - targets)
    loss = ce_loss * ((1 - p_t) ** gamma)
````

**Comment by kadirnar** [comment]
Detectron is a very bad library. The reason for this error is Torch and Cuda versions. I couldn't find the correct version. You can use this code to solve the error.

```
!pip install -U sahi
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
```
![image](https://user-images.githubusercontent.com/36204372/193137036-9b187c91-e29a-4aca-b945-58161c2a07b6.png)

For Detectron Error Messages:
https://github.com/facebookresearch/detectron2/blob/main/INSTALL.md#common-installation-issues

**Comment by aymanaboghonim** [comment]
To avoid any mismatching between torch and cuda, you should install them from official site as pairs 
https://pytorch.org/get-started/previous-versions/.
i.e: `pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113`
